name: Deploy .NET API to Render

on:
  push:
    branches:
      - master
    paths-ignore:
      - 'README.md'
      - 'backend/.gitignore'
      - 'frontend/.gitignore'

jobs:
  deploy-to-render:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Deploy .NET API to Render
        uses: JorgeLNJunior/render-deploy@v1.4.4
        with:
          service_id: ${{ secrets.RENDER_SERVICE_ID }}
          api_key: ${{ secrets.RENDER_API_KEY }}
          clear_cache: false
          wait_deploy: true
          github_deployment: false
          deployment_environment: "production"
          github_token: ${{ secrets.GH_PAT }}